<a href="https://colab.research.google.com/github/SaiVarun1125/Big-Data-Analytics/blob/main/ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Installing numpy
pip install numpy


In [2]:
#Importing numpy library as np
import numpy as np

In [24]:
#Using random to get the random integers in the range of 1 to 20 of size 15.
a= np.random.randint(1,20,size=15)
print(a)


[18  8 17 17 12 11 12 17 12 19 15  4  6  1 17]


In [25]:
#Reshaping the above list into a 3 X 5 Matrix
b=a.reshape(3,5)
print(b)

[[18  8 17 17 12]
 [11 12 17 12 19]
 [15  4  6  1 17]]


In [26]:
#Printing out the shape of the array
c=b.shape
print(c)

(3, 5)


In [27]:
#Finding out the maximum value in the rows
maxval=b.max(axis=1)
#Marking true for the max value in row.
mask = (b == maxval[:, np.newaxis])
#Assigning 0 to the max value positon.
b[mask] = 0
#Printing the output.
print(b)

[[ 0  8 17 17 12]
 [11 12 17 12  0]
 [15  4  6  1  0]]


Question 2

In [29]:
#Creating a list named x
x=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
#Converting the list into a array and assigning it to y
y=np.array(x)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
#Printing the shape of Y
print(y.shape)

(4, 3)


In [32]:
#Printing the data type of Y
print(y.dtype)

int64


In [34]:
#Printing the type of Y
print(type(y))

<class 'numpy.ndarray'>


Question 3

In [35]:
#Creating a list ar
ar=[[0,1,2],[3,4,5]]
#Converting the list into array
new_ar=np.array(ar)
#Printing the new array
print(new_ar)

[[0 1 2]
 [3 4 5]]


In [51]:
z=np.trace(new_ar)
#Using trace() to get the sum of diagonal elements.
print(z)

4


Question 4


In [56]:
#Generating odd values in the range of 10 to 70.
odd=np.arange(10,70,3)
#Priting out the values generated.
print(odd)
#Resizing the above output to fit into a 3 X 3 matrix.
up_odd=np.resize(odd,(3,3))
#Printing the required output
print(up_odd)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67]
[[10 13 16]
 [19 22 25]
 [28 31 34]]


In [57]:
#Generating even values in the range of 10 to 70.
even=np.arange(10,70,2)
#Priting out the generated values.
print(even)
#Resizing the above output to fit into a 3 X 3 matrix.
up_even=np.resize(even,(3,3))
#Printing the required output
print(up_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68]
[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [58]:
#Performing the addition operation on both even, odd matrices and assiging the output to add variable.
add=up_odd+up_even
#Priting the output.
print(add)

[[20 25 30]
 [35 40 45]
 [50 55 60]]


In [60]:
#Performing the subtraction operation on both even, odd matrices and assiging the output to sub variable.
sub=up_odd-up_even
#Priting the output.
print(sub)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [61]:
#Performing the multiplication operation operation on both even, odd matrices and assigning the output to mul variable.
mul=up_odd*up_even
#Priting output.
print(mul)

[[100 156 224]
 [304 396 500]
 [616 744 884]]


In [64]:
#Assiging values to newar
newar= [[5.54, 3.38, 7.99],
 [3.54, 4.38, 6.99],
 [1.54, 2.39, 9.29]]


In [65]:
#Converting newar to array and assiging it to neww.
neww=np.array(newar)

In [70]:
#Sorting Columns.
np.sort(neww,axis=0)

array([[1.54, 2.39, 6.99],
       [3.54, 3.38, 7.99],
       [5.54, 4.38, 9.29]])

In [71]:
#Sorting Rows.
np.sort(neww,axis=1)

array([[3.38, 5.54, 7.99],
       [3.54, 4.38, 6.99],
       [1.54, 2.39, 9.29]])

Question 5

In [84]:
#Assigning values to variable last.
last= np.array([[ 4, 2, np.nan, 1],
[11 ,12 ,14 ,9],
 [5, np.nan, 1, np.nan]])
#Finding out the values nan in last marking them as False and integers as True by using ~isnan().
bol = ~np.isnan(last)
#Priting output.
print(bol)

[[ True  True False  True]
 [ True  True  True  True]
 [ True False  True False]]
